---
- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ target_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Fetch GitHub SSH keys
  uri:
    url: "https://github.com/{{ item }}.keys"
    return_content: yes
  loop: "{{ github_users }}"
  register: github_keys

- name: Add all keys to authorized_keys at once
  blockinfile:
    path: "/home/{{ target_user }}/.ssh/authorized_keys"
    block: |
      {% for item in github_keys.results if item.content|length > 0 %}
      {{ item.content }}
      {% endfor %}
    create: yes
    mode: "0600"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
