---
- become: yes # sudo権限を使用

  block:
    - name: Wait for apt lock
      shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done
      timeout: 300

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Graphviz and GV
      apt:
        name:
          - graphviz
          - gv
        state: present
      when: ansible_os_family == "Debian"

    - name: Verify Graphviz installation
      command: dot -V
      register: graphviz_version
      changed_when: false

    - name: Display Graphviz version
      debug:
        var: graphviz_version.stderr_lines
