---
# TODO initial_setup.sh を見ながら追加したほうがよさそうな処理を追加

- name: Tasks for add_github_ssh_keys
  include_tasks: add_github_ssh_keys.yml

- name: Tasks for install_redis.yml
  include_tasks: install_redis.yml

- name: Tasks for install_alp
  include_tasks: install_alp.yml

- name: Tasks for install_slp
  include_tasks: install_slp.yml

- name: Tasks for setup_pprotein
  include_tasks: setup_pprotein.yml

- name: Tasks for install_graphviz
  include_tasks: install_graphviz.yml

- name: Install fish shell
  apt:
    name: fish
    state: present
  become: yes

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install glances
  pip:
    name: glances
    state: present
  become: yes
