---
# TODO initial_setup.sh を見ながら追加したほうがよさそうな処理を追加

# - name: Tasks for add_github_ssh_keys
#   include_tasks: add_github_ssh_keys.yml

- name: Tasks for install_redis.yml
  include_tasks: install_redis.yml

- name: Tasks for install_alp
  include_tasks: install_alp.yml

- name: Tasks for install_slp
  include_tasks: install_slp.yml

- name: Tasks for setup_pprotein
  include_tasks: setup_pprotein.yml

- name: Tasks for install_graphviz
  include_tasks: install_graphviz.yml

- name: Install fish shell
  apt:
    name: fish
    state: present
  become: yes

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install glances
  pip:
    name: glances
    state: present
  become: yes

- name: Install pt-query-digest
  apt:
    name: percona-toolkit
    state: present
  become: yes

- name: Download tmux config file
  get_url:
    url: "https://raw.githubusercontent.com/wataruiwabuchi/tmux_config/master/.tmux.conf"
    dest: "/home/{{ target_user }}/.tmux.conf"
    mode: '0644'
    force: yes

- name: Download vim config file
  get_url:
    url: "https://raw.githubusercontent.com/wataruiwabuchi/vim_config/master/.vimrc"
    dest: "/home/{{ target_user }}/.vimrc"
    mode: '0644'
    force: yes