---
# NOTE 9000 番で起動
- become: yes
  vars:
    pprotein_version: "1.2.3"
    pprotein_url: "https://github.com/kaz/pprotein/releases/download/v{{ pprotein_version }}/pprotein_{{ pprotein_version }}_linux_amd64.tar.gz"
    pprotein_install_path: "/usr/local/bin"

  block:
    - name: Check if PProtein is already installed
      command: which pprotein
      register: pprotein_check
      ignore_errors: yes
      changed_when: false

    - name: Set fact for PProtein installation status
      set_fact:
        pprotein_installed: "{{ pprotein_check.rc == 0 }}"

    - name: Download PProtein
      get_url:
        url: "{{ pprotein_url }}"
        dest: "/tmp/pprotein.tar.gz"
        mode: "0644"
      when: not pprotein_installed

    - name: Extract PProtein
      unarchive:
        src: "/tmp/pprotein.tar.gz"
        dest: "{{ pprotein_install_path }}"
        remote_src: yes
      when: not pprotein_installed

    - name: Clean up downloaded archive
      file:
        path: "/tmp/pprotein.tar.gz"
        state: absent
      when: not pprotein_installed

    - name: Create PProtein service file
      copy:
        content: |
          [Unit]
          Description=pprotein service

          [Service]
          ExecStart={{ pprotein_install_path }}/pprotein
          WorkingDirectory={{ pprotein_install_path }}
          Environment=PATH=$PATH:/usr/local/bin
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/pprotein.service"
        mode: "0644"

    - name: Create PProtein agent service file
      copy:
        content: |
          [Unit]
          Description=pprotein-agent service

          [Service]
          ExecStart={{ pprotein_install_path }}/pprotein-agent
          WorkingDirectory={{ pprotein_install_path }}
          Environment=PATH=$PATH:/usr/local/bin
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/pprotein-agent.service"
        mode: "0644"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start PProtein service
      systemd:
        name: pprotein
        state: started
        enabled: yes

    - name: Start PProtein agent service
      systemd:
        name: pprotein-agent
        state: started
        enabled: yes

    # NOTE service を起動するとデフォルトファイルが作成されるのでその後に上書き
    - name: Create PProtein targets.json
      copy:
        content: |
          [
            {
              "Type": "pprof",
              "Label": "localhost",
              "URL": "http://localhost:8080/debug/pprof/profile",
              "Duration": 60
            },
            {
              "Type": "httplog",
              "Label": "localhost",
              "URL": "http://localhost:9000/debug/log/httplog",
              "Duration": 60
            },
            {
              "Type": "slowlog",
              "Label": "localhost",
              "URL": "http://localhost:9000/debug/log/slowlog",
              "Duration": 60
            }
          ]
        dest: "{{ pprotein_install_path }}/data/targets.json"
        mode: "0644"

    - name: Create PProtein alp config file
      copy:
        content: |
          matching_groups:
            - ^/api/user/[0-9a-zA-Z_-]+/theme$
            - ^/api/user/[0-9a-zA-Z_-]+/livestream$
            - ^/api/livestream/[0-9a-f_-]+$
            - ^/api/livestream/[0-9a-f_-]+/livecomment$
            - ^/api/livestream/[0-9a-f_-]+/reaction$
            - ^/api/livestream/[0-9a-f_-]+/report$
            - ^/api/livestream/[0-9a-f_-]+/ngwords$
            - ^/api/livestream/[0-9a-f_-]+/livecomment/[0-9a-f_-]+/report$
            - ^/api/livestream/[0-9a-f_-]+/moderate$
            - ^/api/livestream/[0-9a-f_-]+/enter$
            - ^/api/livestream/[0-9a-f_-]+/exit$
            - ^/api/user/[0-9a-zA-Z_-]+$
            - ^/api/user/[0-9a-zA-Z_-]+/statistics$
            - ^/api/user/[0-9a-zA-Z_-]+/icon$
            - ^/api/livestream/[0-9a-f_-]+/statistics$
        dest: "{{ pprotein_install_path }}/alp.yml"
        mode: "0644"
