---
- name: Ensure destination directories exist
  file:
    path: "{{ item | dirname }}"
    state: directory
    mode: "{{ default_dir_mode }}"
  loop: "{{ managed_files }}"

- name: Synchronize files back to their destinations
  synchronize:
    src: "{{ local_collection_path }}/"
    dest: "{{ item | dirname }}/"
    mode: push
    delete: no
    # rsync_opts:
    #   - "--include={{ item | basename }}"
    #   - "--exclude=*"
  loop: "{{ managed_files }}"

- name: Build the application
  command: make
  args:
    chdir: "{{ build_path }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ go_path }}"

- name: Restart related services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop: "{{ service_names }}"
