---
- name: Ensure local collection directory exists
  file:
    path: "{{ local_collection_path }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  become: no

# NOTE エラーになることがあるので事前に作成
- name: Create parent directories for each path
  file:
    path: "{{ local_collection_path }}{{ item | dirname }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  become: no
  loop: "{{ managed_files }}"

# NOTE fetch だとディレクトリ構造に host name の情報も含まれて辛かったので sync を使う、ディレクトリも指定可能
- name: Collect files and directories
  synchronize:
    src: "{{ item }}"
    dest: "{{ local_collection_path }}{{ item | dirname }}/"
    mode: pull
    recursive: yes
  loop: "{{ managed_files }}"
