---
- name: Ensure local collection directory exists
  file:
    path: "{{ local_collection_path }}"
    state: directory
    mode: "{{ default_dir_mode }}"
  delegate_to: localhost

# NOTE fetch だとディレクトリ構造に host name の情報も含まれて辛かったので sync を使う、ディレクトリも指定可能
- name: Sync files from remote servers preserving directory structure without host information
  synchronize:
    src: "{{ item }}"
    dest: "{{ local_collection_path }}/"
    mode: pull
    delete: no
    recursive: yes
    links: yes
    relative: yes
    archive: yes
    owner: yes
    group: yes
  loop: "{{ managed_files }}"

- name: Display collected files
  debug:
    msg: "Collected file: {{ item }}"
  loop: "{{ managed_files }}"
  delegate_to: localhost