---
all:
  children:
    web:
      hosts:
        web1:
          ansible_host: 35.72.3.48
    db:
      hosts: {}
  vars:
    max_parallel_jobs: 10
    ansible_user: isucon

    # 収集および配布するファイルのリスト
    # 現状ファイルしか指定できないので全部列挙する
    managed_files:
      - /etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled/isupipe.conf
      - /etc/mysql/mysql.conf.d/mysqld.cnf
      - /etc/systemd/system/isuports.service
      - /home/isucon/webapp/go
      - /home/isucon/webapp/sql
      - /home/isucon/webapp/docker-compose-go.yml

    # ローカルでの収集ファイルの保存先
    local_collection_path: "{{ playbook_dir }}/collected_files"

    # ファイルのデフォルトモード
    default_file_mode: '0644'
    default_dir_mode: '0755'

    # アプリケーション関連の変数
    service_names:
      - mysql
      - nginx
      - isupipe-go