---
all:
  children:
    web:
      hosts:
        web1:
          ansible_host: xxx.xxx.xxx.xxx
    db:
      hosts: {}
  vars:
    max_parallel_jobs: 10
    ansible_user: isucon

    # 収集および配布するファイルのリスト
    # 現状ファイルしか指定できないので全部列挙する
    managed_paths:
      - /etc/nginx/nginx.conf
      - /etc/nginx/sites-available/isucon.conf
      - /etc/mysql/mysql.conf.d/mysqld.cnf
      - /home/isucon/private_isu/webapp/golang/templates/post_id.html
      - /home/isucon/private_isu/webapp/golang/templates/user.html
      - /home/isucon/private_isu/webapp/golang/templates/post.html
      - /home/isucon/private_isu/webapp/golang/templates/banned.html
      - /home/isucon/private_isu/webapp/golang/templates/posts.html
      - /home/isucon/private_isu/webapp/golang/templates/login.html
      - /home/isucon/private_isu/webapp/golang/templates/layout.html
      - /home/isucon/private_isu/webapp/golang/templates/index.html
      - /home/isucon/private_isu/webapp/golang/templates/register.html
      - /home/isucon/private_isu/webapp/golang/Makefile
      - /home/isucon/private_isu/webapp/golang/app
      - /home/isucon/private_isu/webapp/golang/.gitignore
      - /home/isucon/private_isu/webapp/golang/app.go
      - /home/isucon/private_isu/webapp/golang/go.sum
      - /home/isucon/private_isu/webapp/golang/setup.sh
      - /home/isucon/private_isu/webapp/golang/go.mod
      - /home/isucon/private_isu/webapp/golang/Dockerfile

    build_path: /home/isucon/webapp/go

    # ローカルでの収集ファイルの保存先
    local_collection_path: "{{ playbook_dir }}/collected_files"

    # ファイルのデフォルトモード
    default_file_mode: '0644'
    default_dir_mode: '0755'

    # アプリケーション関連の変数
    service_names:
      - mysql
      - nginx
      - isu-go